### ISSUE TITLE
Hello. I had some problems, when used this library.

### ISSUE THREAD

**Issue by AliNamibi** [Alexandro1112/driver_controller#1]
Here my code.

```
import driver_controller._mac_engine

Play = driver_controller._mac_engine.MacCmd().Sound()
Play.playSoundByName(soundfile='sound.wma')
```
And error:

```
Traceback (most recent call last):
  File "/Users/admin/PycharmProjects/pythonProject2/driver_controller/_mac_engine.py", line 901, in playSoundByName
    self.duration_Start.play()
AttributeError: 'NoneType' object has no attribute 'play'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/admin/PycharmProjects/Github/main.py", line 4, in <module>
    Play.playSoundByName(soundfile='sound.wma')
  File "/Users/admin/PycharmProjects/Github/driver_controller/_mac_engine.py", line 907, in playSoundByName
    raise PathError() from e
driver_controller.exceptions.PathError
```
How to solve this?

**Comment by Alexandro1112** [comment]
Hello, Ali.This error happened because of nonexistent of file. Firstly,  add audio file
> sound.wma

 in working directory, and after - run code.
